### ISSUE TITLE
Plugin 'Debug Variable Extractor' (version 2.4.0) was explicitly marked as incompatible with the current version of the IDE

### ISSUE THREAD

**Issue by mathisgauthey** [chocovon/debug-variable-extractor#4]
Hey there, is there a possibility to make this plugin available on IntelliJ Ultimate 2024.3 ?

Thanks in advance !

**Comment by chocovon** [comment]
I've already uploaded a fix upgrade to the platform, but the reviewer said the plugin uses an API which has been marked as "internal" since 2024.3. He has sent a request to the dev team to help find the solution, but there is still no response till now...

Maybe I should try some workaround later :/

**Comment by chocovon** [comment]
It's available now in 2024.3.
